### ISSUE TITLE
error[E0635]: unknown feature `stdsimd`

### ISSUE THREAD

**Issue by ArunGust** [tkaitchuck/aHash#200]
unknown feature `stdsimd` : Got below after updating rust to new version rustc 1.78.0-nightly (f067fd608 2024-02-05)
========================

error[E0635]: unknown feature `stdsimd`
  --> C:\SYSTEM\RUST\CARGO\registry\src\index.crates.io-6f17d22bba15001f\ahash-0.7.7\src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error

**Comment by tusharmath** [comment]
Facing similar issue.

**Comment by tmpfs** [comment]
Same here on version 0.7.7, it's broken my crate's documentation build on docs.rs but works fine for me locally on Linux and MacOS, not sure why it's only broken in the docs.rs sandbox environment.

**Comment by Kobzol** [comment]
This is caused by https://github.com/rust-lang/rust/pull/117372. This problem in ahash was already fixed in https://github.com/tkaitchuck/aHash/pull/183, but a new release hasn't been released yet. CC @tkaitchuck

**Comment by RalfJung** [comment]
Fundamentally this is caused by logic in build.rs that auto-enables a nightly feature when it detects that it is built with a nightly rustc. Such logic is fragile and prone to errors as nightly features evolve before stabilization.

Crates should never automatically enable nightly features, this should generally be opt-in. If they try to do it automatically they need to be very careful and account for the fact that nightly features are not stable, and might look very different in future nightly versions.

**Comment by humb1t** [comment]
Same for me

**Comment by mina86** [comment]
If you’re on 0.8 branch → update to 0.8.7.  See #188.

However, I’m also picking up dependency on 0.7.7 through chain of older dependencies (borsh 0.9 → hashbrown 0.11 → ahash 0.7) which I can’t easily get rid of on my side.  It’d be fantastic if we could get backport to 0.7 branch as well.  I’ve commented that in #188.

**Comment by vikingSec** [comment]
Seems like this is breaking `trunk` and `leptos`

I was just trying to get into learning leptos, so installing all of the right versions according to [the docs](https://book.leptos.dev/getting_started/index.html) and trying to install trunk and cargo-leptos both runs into this bug.

Console output:
```
> cargo install trunk
error[E0635]: unknown feature `stdsimd`
  --> /Users/medwards/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.7.7/src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `trunk v0.18.7`, intermediate artifacts can be found at `/var/folders/9f/w50rg2wj193fh6jv5rt0lk1r0000gn/T/cargo-installif2CRL`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.```

Not trying to brigade the comments, I'd work on a fix but you probably don't want a Rust noop running around your repo.

**Comment by vikingSec** [comment]
> It seems that _a lot_ of stuff depends on `ahash` < 0.8. It would be indeed useful if it was possible to put out a backported patch release for `0.7`.

Can confirm that `cargo-leptos` and `trunk` both depend on v0.7.7 and don't work now.

**Comment by Manishearth** [comment]
@tkaitchuck Would it be possible to remove the build.rs check in the 0.7 series? 0.8 fixes this but:

 - Not everyone has upgraded to it
 - This affects MSRV

> Fundamentally this is caused by logic in build.rs that auto-enables a nightly feature when it detects that it is built with a nightly rustc. Such logic is fragile and prone to errors as nightly features evolve before stabilization.



I agree with Ralf here: crates shouldn't do this. It makes life harder for crates attempting to support a range of versions: they're either broken on the new version due to the missing feature, or broken on the old version due to an unstable feature.

**Comment by Manishearth** [comment]
Opened https://github.com/tkaitchuck/aHash/pull/202

Looks like this feature was already disabled in https://github.com/tkaitchuck/aHash/pull/183

**Comment by Kobzol** [comment]
Same as https://github.com/tkaitchuck/aHash/pull/201?

**Comment by Manishearth** [comment]
Almost. https://github.com/tkaitchuck/aHash/pull/202 gets us out of the detection business entirely, which is what was already landed in #183

**Comment by janu-cambrelen** [comment]
For those in this situation and if your workflow permits, pinning the Rust nightly version to an earlier date might serve as a temporary measure to get unblocked, particularly if you're facing the `unknown feature 'stdsimd'` error with `ahash-0.7.7`:

```sh
# install specific nightly version (i.e., `2024-02-01`)
rustup toolchain install nightly-2024-02-01

# use this nightly version for your commands
cargo +nightly-2024-02-01 build
```

This is not, of course, a solution to the issue, but rather a workaround that may help in the interim until a more permanent fix is available.

**Comment by ozgrakkurt** [comment]
Why not juse use crates.io version of the thing or something like that? This is a huge pain, all of the dependencies are littered with this and it is impossible to compile on an M1 with stable toolchain

**Comment by tkaitchuck** [comment]
Fixed via #201, and released as 0.7.8

**Comment by Temidayo32** [comment]
I am still experiencing the issue. I installed the latest stable

**Comment by scambier** [comment]
> I am still experiencing the issue. I installed the latest stable

Working for me with 0.8.8. Don't forget to `cargo clean`

**Comment by Kobzol** [comment]
Don't forget that you have to `cargo update ahash` to actually get the newest version (either `0.7.8` or `0.8.7`+).

**Comment by marvin-bitterlich** [comment]
Thank you everyone for the quick resolution!

For folks who have both versions in their deps, here is a quick fix that doesn't require clean:

```
cargo update ahash@0.8
cargo update ahash@0.7
```

**Comment by HKby** [comment]
The issue fixed when version 0.8.7 
I have fixed with workspace root Cargo.toml
`[workspace.dependencies]
ahash = "0.8.7"

[workspace.metadata.resolver]
version = "2"`

program Cargo.toml
`ahash = { workspace = true }`

**Comment by explorer-Sanjita** [comment]
I am facing the same issue
